### ISSUE TITLE
Collision Chamber can't produce anti-proton

### ISSUE THREAD

**Issue by acelel** [MechOrigin/NTC2#52]
The collision chamber recipe for anti proton (Liquid Proton + Molten Lead) is not working. Only the Liquid Proton gets used and liquid Positron is crafted.

Editing custommachinery_recipes.js so that the anti-proton recipe comes first seems to fix the issue.

**Comment by Dasffion** [comment]
Bumped for posterity. Adding Oxygen back into the recipe would also fix it.

**Comment by MechOrigin** [comment]
Can anyone confirm that this issue is fixed now in alpha 1.4.2 (the github repo currently)?

**Comment by Overseer9** [comment]
Already update to 1.4.2 here
Still doesn't seem to be able to produce anti-proton
